# Generated by Django 4.2.6 on 2023-10-22 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nombre del autor')),
                ('registration_year', models.DateField(verbose_name='Fecha de registro')),
                ('birthdate', models.DateField(verbose_name='Fecha de nacimiento')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Languaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nombre de la editorial')),
                ('registration_year', models.DateField(verbose_name='Fecha de registro')),
                ('format', models.CharField(choices=[('HARD', 'Pasta dura'), ('SOFT', 'Pasta suave'), ('DIGITAL', 'Digital'), ('SOUND', 'Audio libros'), ('UNKNOW', 'Desconocido')], max_length=16, verbose_name='Formato de públicación')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.gender', verbose_name='Género')),
                ('languaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.languaje', verbose_name='Idioma principal')),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nombre del libro')),
                ('edition', models.IntegerField(verbose_name='Edición')),
                ('isbn', models.CharField(max_length=32, verbose_name='ISBN')),
                ('publication_date', models.DateField(verbose_name='Fecha de publicación (Se ignorará el día)')),
                ('number_of_books', models.IntegerField(default=1)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogo.author', verbose_name='Autor')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.editorial', verbose_name='Editorial')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.gender', verbose_name='Género')),
                ('languaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.languaje', verbose_name='Idioma principal')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.gender', verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='author',
            name='languaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.languaje', verbose_name='Idioma principal'),
        ),
    ]
