# Generated by Django 4.2.6 on 2023-10-22 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping_car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nombre(s)')),
                ('first_last_name', models.CharField(max_length=32, verbose_name='Apellido paterno')),
                ('second_last_name', models.CharField(max_length=32, verbose_name='Apellido materno')),
                ('assigned_car', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping_car.shoppingcar', verbose_name='Carrito asignado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
