# Generated by Django 4.2.7 on 2023-11-30 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        default="", max_length=32, verbose_name="Nombre completo"
                    ),
                ),
                (
                    "tarjeta",
                    models.CharField(
                        default="", max_length=32, verbose_name="Número de tarjeta"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Lista de clientes",
            },
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        default="", max_length=32, verbose_name="Nombre del libro"
                    ),
                ),
                (
                    "isbn",
                    models.CharField(default="", max_length=32, verbose_name="ISBN"),
                ),
                ("precio", models.IntegerField(default=0, verbose_name="Precio")),
                ("cantidad", models.IntegerField(default=0, verbose_name="Cantidad")),
            ],
            options={
                "verbose_name": "Libro",
                "verbose_name_plural": "Lista de libros",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tarjeta",
                    models.CharField(
                        default="1234 1234 1234 1234",
                        max_length=32,
                        verbose_name="Tarjeta",
                    ),
                ),
                ("compras", models.CharField(max_length=512, verbose_name="Compras")),
                (
                    "nombre_comprador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liberria.cliente",
                        verbose_name="Comprador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Lista de tickets",
            },
        ),
        migrations.CreateModel(
            name="Carrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField(default=0, verbose_name="Cantidad")),
                (
                    "libro_comprado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liberria.libro",
                        verbose_name="Libro comprado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrito",
                "verbose_name_plural": "Lista de compras",
            },
        ),
    ]
